// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.11
// source: gRPC/interface.proto

package hashmap

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// HashmapClient is the client API for Hashmap service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type HashmapClient interface {
	Put(ctx context.Context, in *PutRequest, opts ...grpc.CallOption) (*PutReply, error)
	Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetReply, error)
}

type hashmapClient struct {
	cc grpc.ClientConnInterface
}

func NewHashmapClient(cc grpc.ClientConnInterface) HashmapClient {
	return &hashmapClient{cc}
}

func (c *hashmapClient) Put(ctx context.Context, in *PutRequest, opts ...grpc.CallOption) (*PutReply, error) {
	out := new(PutReply)
	err := c.cc.Invoke(ctx, "/hashmap.Hashmap/put", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hashmapClient) Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetReply, error) {
	out := new(GetReply)
	err := c.cc.Invoke(ctx, "/hashmap.Hashmap/get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HashmapServer is the server API for Hashmap service.
// All implementations must embed UnimplementedHashmapServer
// for forward compatibility
type HashmapServer interface {
	Put(context.Context, *PutRequest) (*PutReply, error)
	Get(context.Context, *GetRequest) (*GetReply, error)
	mustEmbedUnimplementedHashmapServer()
}

// UnimplementedHashmapServer must be embedded to have forward compatible implementations.
type UnimplementedHashmapServer struct {
}

func (UnimplementedHashmapServer) Put(context.Context, *PutRequest) (*PutReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Put not implemented")
}
func (UnimplementedHashmapServer) Get(context.Context, *GetRequest) (*GetReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedHashmapServer) mustEmbedUnimplementedHashmapServer() {}

// UnsafeHashmapServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HashmapServer will
// result in compilation errors.
type UnsafeHashmapServer interface {
	mustEmbedUnimplementedHashmapServer()
}

func RegisterHashmapServer(s grpc.ServiceRegistrar, srv HashmapServer) {
	s.RegisterService(&Hashmap_ServiceDesc, srv)
}

func _Hashmap_Put_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HashmapServer).Put(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/hashmap.Hashmap/put",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HashmapServer).Put(ctx, req.(*PutRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Hashmap_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HashmapServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/hashmap.Hashmap/get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HashmapServer).Get(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Hashmap_ServiceDesc is the grpc.ServiceDesc for Hashmap service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Hashmap_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "hashmap.Hashmap",
	HandlerType: (*HashmapServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "put",
			Handler:    _Hashmap_Put_Handler,
		},
		{
			MethodName: "get",
			Handler:    _Hashmap_Get_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "gRPC/interface.proto",
}
